---
sub_dir_path: rq4.0
performance:
  predict_forward: 10000
  n_jobs:
    model: -1
    simulator: -1
evaluation_params:
  batch_size: 20000
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params: {}
common_runs_params:
  training_step_size: 5000
  first_train_window_size: -1
  test_start_idx: 400000
runs:
  - name: periodic
    random_state:
      grid: [42]
    type: baseline
    detectors:
      - name: periodic
        params:
          period:
            grid: [5000, 10000, 20000, 50000, 100000, 200000, 400000]
    model:
      source: drift_study.model_arch.tree_model
      name:
        grid: [rf_lcld_400]
    train_window_size:
      grid: [200000]
    delays:
      grid:
        - label: 10days
          drift: 0
          retraining: 2W
        - label: 10days
          drift: 0
          retraining: 8W
