common_detectors_params: {}
common_runs_params:
  first_train_window_size: -1
  test_start_idx: 400000
  train_window_size: 400000
  training_step_size: 5000
dataset:
  name: lcld_201317_ds_time
evaluation_params:
  batch_size: 20000
  metric:
    name: mcc
  n_score: 2
performance:
  n_jobs:
    model: -1
    simulator: 1
  predict_forward: 20000
runs:
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 20000
  model:
    name: rf_lcld
    source: drift_study.model_arch.tree_model
  name: periodic_42_20000_rf_lcld_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 20000
  model:
    name: rf_lcld_400
    source: drift_study.model_arch.tree_model
  name: periodic_42_20000_rf_lcld_400_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 20000
  model:
    name: opt_rf_classifier
    source: drift_study.model_arch.tree_model
  name: periodic_42_20000_opt_rf_classifier_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 50000
  model:
    name: rf_lcld
    source: drift_study.model_arch.tree_model
  name: periodic_42_50000_rf_lcld_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 50000
  model:
    name: rf_lcld_400
    source: drift_study.model_arch.tree_model
  name: periodic_42_50000_rf_lcld_400_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 50000
  model:
    name: opt_rf_classifier
    source: drift_study.model_arch.tree_model
  name: periodic_42_50000_opt_rf_classifier_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 100000
  model:
    name: rf_lcld
    source: drift_study.model_arch.tree_model
  name: periodic_42_100000_rf_lcld_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 100000
  model:
    name: rf_lcld_400
    source: drift_study.model_arch.tree_model
  name: periodic_42_100000_rf_lcld_400_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 100000
  model:
    name: opt_rf_classifier
    source: drift_study.model_arch.tree_model
  name: periodic_42_100000_opt_rf_classifier_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 200000
  model:
    name: rf_lcld
    source: drift_study.model_arch.tree_model
  name: periodic_42_200000_rf_lcld_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 200000
  model:
    name: rf_lcld_400
    source: drift_study.model_arch.tree_model
  name: periodic_42_200000_rf_lcld_400_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 200000
  model:
    name: opt_rf_classifier
    source: drift_study.model_arch.tree_model
  name: periodic_42_200000_opt_rf_classifier_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 400000
  model:
    name: rf_lcld
    source: drift_study.model_arch.tree_model
  name: periodic_42_400000_rf_lcld_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 400000
  model:
    name: rf_lcld_400
    source: drift_study.model_arch.tree_model
  name: periodic_42_400000_rf_lcld_400_0
  random_state: 42
  type: baseline
- delays:
    drift: 0
    label: 0
    retraining: 0
  detectors:
  - name: periodic
    params:
      period: 400000
  model:
    name: opt_rf_classifier
    source: drift_study.model_arch.tree_model
  name: periodic_42_400000_opt_rf_classifier_0
  random_state: 42
  type: baseline
sub_dir_path: rq1.2
