---
sub_dir_path: rq1.2
performance:
  predict_forward: 20000
  n_jobs:
    model: -1
    simulator: 1
evaluation_params:
  batch_size: 20000
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params: {}
common_runs_params:
  training_step_size: 5000
  first_train_window_size: -1
  test_start_idx: 400000
  train_window_size: 400000
runs:
  - name: periodic
    random_state:
      grid: [42]
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 
            grid: [20000, 50000, 100000, 200000, 400000]
    model:
      source: drift_study.model_arch.tree_model
      name:
        grid: [rf_lcld, rf_lcld_400, opt_rf_classifier]
    delays:
      grid:
        - label: 0
          drift: 0
          retraining: 0
