---
performance:
  predict_forward: 5000
  n_jobs:
    model: -1
    simulator: -1
    optimizer: -1
experience:
  random_state: 42
evaluation_params:
  batch_size: 20000
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  batch_size: 5000
common_runs_params:
  first_train_window_size: -1
  training_step_size: 5000
  test_start_idx: 400000
  train_window_size: 200000
  random_state: 42
  model:
    source: drift_study.model_arch.tree_model
    name: rf_lcld_400
  delays:
    label: 10days
    drift: 0
    retraining: 4W