---
logging:
  version: 1
  formatters:
    simple:
      format: '[%(levelname)-.4s] %(asctime)s - %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    __main__:
      level: INFO
    optuna:
      level: ERROR
  root:
    level: DEBUG
    handlers: [console]
